// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var all_count, check, comp_box, comp_text, count, game_clear, pieces, reset;
    pieces = $('.btn-munipiece');
    comp_box = $('#comp-puzzle');
    comp_text = '';
    all_count = $('.btn-munipiece').size();
    count = 0;
    pieces.click(function() {
      $(this).hide();
      comp_text += $(this).html();
      comp_box.html(comp_text);
      count++;
      if (count === all_count) {
        return check();
      }
    });
    check = function() {
      if (comp_text === "(ﾉ)・ω・(ヾ)") {
        return game_clear();
      } else {
        return reset();
      }
    };
    reset = function() {
      var clone;
      pieces.each(function() {
        return $(this).show();
      });
      clone = comp_box.clone(true);
      clone.removeAttr("id");
      $('#result-box').prepend(clone);
      count = 0;
      comp_text = "";
      return comp_box.html("");
    };
    return game_clear = function() {
      $('#happy').slideDown();
      comp_box.addClass("ok");
      return $('#powered-by').show();
    };
  });

}).call(this);
